spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
    username: C##DATASOURCE
    password: pwd
    driver-class-name: oracle.jdbc.OracleDriver
  output:
    ansi:
      enabled: always
test-env:
  env-name: local
  datasource-ui:
    url: localhost
    port: 8081
  implicit-wait: 1
  explicit-wait: 10
  wait: 10
  fail-fast: true
aws:
  sns:
    topicArn: ""
---
spring:
  profiles: qa
  datasource:
    url: jdbc:oracle:thin:@oracle-db.co6e722tselv.ap-southeast-1.rds.amazonaws.com:1521:ALLOT
    username: datasource_qa
    password: perMaNalTY
test-env:
  env-name: qa
  datasource-ui:
    url: https://datasource-qa.cpfb.gds-gov.tech
  implicit-wait: 5
  explicit-wait: 30
  wait: 600
  fail-fast: false
aws:
  sns:
    topicArn: "arn:aws:sns:ap-southeast-1:026083545547:slack-topic"