spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
    username: C##DATASOURCE
    password: pwd
    driver-class-name: oracle.jdbc.OracleDriver
  output:
    ansi:
      enabled: always
test-env:
  env-name: local
  datasource:
    url: localhost
    port: 8081
  datasource-ui:
    url: localhost
    port: 4200
    username: cdit
    password: cdit
  implicit-wait: 1
  explicit-wait: 10
  wait: 10
  fail-fast: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
aws:
  sns:
    topicArn: ""
---
spring:
  profiles: automation
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
    username: C##DATASOURCE
    password: pwd
    driver-class-name: oracle.jdbc.OracleDriver
test-env:
  env-name: automation
  datasource:
    url: https://datasource-qa.cpfb.gds-gov.tech
    port: 8081
  datasource-ui:
    url: localhost
    port: 4200
    username: cdit
    password: cdit
  implicit-wait: 5
  explicit-wait: 30
  wait: 600
  fail-fast: false
aws:
  sns:
    topicArn: ""
---
spring:
  profiles: qa
  datasource:
    url: jdbc:oracle:thin:@//cdsracdev-scan.cpfb.gds-gov.tech:1625/allot.cpfb.gds-gov.tech
    username: Datasource
    password: Ft2FUEA$GPyUx^
    driver-class-name: oracle.jdbc.driver.OracleDriver
test-env:
  env-name: qa
  datasource:
    url: https://datasource-qa.cpfb.gds-gov.tech
    port: 8081
  datasource-ui:
    url: localhost
    port: 4200
    username: cdit
    password: cdit
  implicit-wait: 5
  explicit-wait: 30
  wait: 600
  fail-fast: false
aws:
  sns:
    topicArn: "arn:aws:sns:ap-southeast-1:026083545547:slack-topic"