package cdit_automation.enums;

public enum BatchStatusEnum {
    INIT("INIT"),
    INIT_ERROR("INIT_ERROR"),
    CHECKING_FILE("CHECKING_FILE"),
    LINE_CHECKED("LINE_CHECKED"),
    LINE_ERROR("LINE_ERROR"),
    FILE_CHECKED("FILE_CHECKED"),
    FILE_ERROR("FILE_ERROR"),
    RAW_DATA("RAW_DATA"),
    RAW_DATA_ERROR("RAW_DATA_ERROR"),
    VALIDATED_DATA("VALIDATED_DATA"),
    VALIDATION_ERROR("VALIDATION_ERROR"),
    BULK_CHECK_VALIDATED_DATA("BULK_CHECK_VALIDATED_DATA"),
    BULK_CHECK_VALIDATION_ERROR("BULK_CHECK_VALIDATION_ERROR"),
    VALIDATED_TO_PREPARED_DATA("VALIDATED_TO_PREPARED_DATA"),
    VALIDATED_TO_PREPARED_ERROR("VALIDATED_TO_PREPARED_ERROR"),
    MAPPED_DATA("MAPPED_DATA"),
    MAPPING_ERROR("MAPPING_ERROR"),
    FILE_CHECK_AGAINST_PREP_DATA("FILE_CHECK_AGAINST_PREP_DATA"),
    FILE_CHECK_AGAINST_PREP_DATA_ERROR("FILE_CHECK_AGAINST_PREP_DATA_ERROR"),
    SENT_DATA("SENT_DATA"),
    SENDING_ERROR("SENDING_ERROR");

    private String value;

    BatchStatusEnum(String s) {
        this.value = s;
    }

    @Override
    public String toString() {
        return this.value;
    }
}
