package automation.enums.datasource;

public enum AssessableIncomeStatus {
  INCOME_ASSESSED("INCOME_ASSESSED"),
  PENDING_ASSESSMENT("PENDING_ASSESSMENT"),
  RECORD_NOT_FOUND("RECORD_NOT_FOUND"),
  AI_0_TO_28K("AI_0_TO_28K"),
  AI_28K_TO_29K("AI_28K_TO_29K"),
  AI_29K_TO_30K("AI_29K_TO_30K"),
  AI_30K_TO_31K("AI_30K_TO_31K"),
  AI_28K_TO_31K("AI_28K_TO_31K"),
  AI_31K_TO_120K("AI_31K_TO_120K"),
  AI_EQUAL_BELOW_120K("AI_EQUAL_BELOW_120K"),
  AI_ABOVE_120K("AI_ABOVE_120K"),
  // Mapping statuses TBC. Will change according to UserStory changes
  INCOME_NOT_ASSESSED_BUT_FOUND_IN_IRAS_DATABASE("INCOME_NOT_ASSESSED_BUT_FOUND_IN_IRAS_DATABASE"),
  NO_INCOME_ASSESSMENT_AND_NOT_FOUND_IN_IRAS_DATABASE(
          "NO_INCOME_ASSESSMENT_AND_NOT_FOUND_IN_IRAS_DATABASE"),
  NO_ASSESSMENT_RECORD_FOUND_RETURN_ISSUED("NO ASSESSMENT RECORD FOUND, RETURN ISSUED."),
  NO_ASSESSMENT_RECORD_FOUND_NO_RETURN_ISSUED("NO ASSESSMENT RECORD FOUND, NO RETURN ISSUED."),
  INVALID_ID("INVALID ID PROVIDED"),
  DEFAULT_ASSESSMENT_FOUND("ID PROVIDED DEFAULTED ON INCOME TAX SUBMISSION, AI NOT FOUND."),
  YEAR_OF_ASSESMENT_OUT_OF_RANGE("YEAR OF ASSESSMENT PROVIDED IS OUT OF RANGE."),
  INVALID_RESULT_INDICATOR("INVALID RESULT INDICATOR FOUND. CANNOT MAP."),
  NEW_APPEAL_CASE("NEW_APPEAL_CASE");

  private String value;

  private AssessableIncomeStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return this.value;
  }
}
